title: Petr Krebs
author: Petr Krebs
subtitle: subtitle

baseurl: ""

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

footer_url: "https://github.com/pro-panda"
footer_text: "Made by pro-panda"

profile-picture: assets/harry.jpg

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
