title: Petr Krebs
author: Petr Krebs
subtitle: personal blog

baseurl: ""

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

footer_url: "https://github.com/pro-panda/sorting-hat"
footer_text: "Made with Jekyll & sorting-hat"

profile-picture: assets/rs-1.jpg

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Blog"
   link: ""
 - name: "About"
   link: "about"
